job: extension
config:
  name: last
  process:
  - type: diffusion_trainer
    training_folder: /app/checkpoints
    device: cuda
    network:
      type: lora
      linear: 128
      linear_alpha: 64
      conv: 32
      conv_alpha: 32
    save:
      dtype: bf16
      save_every: 250
      max_step_saves_to_keep: 4
      save_format: diffusers
    datasets:
    - folder_path: /dataset/images
      caption_ext: txt
      cache_latents_to_disk: true
      resolution: [512, 768, 1024]
      is_reg: false
    train:
      batch_size: 1
      steps: 1600
      lr: 0.0002
      optimizer: adamw8bit
      gradient_checkpointing: true
      gradient_accumulation: 4
      noise_scheduler: flowmatch
      timestep_type: weighted
      dtype: bf16
    model:
      name_or_path: /cache/models
      arch: zimage:turbo
      quantize: false
      qtype: qfloat8
      quantize_te: false
      qtype_te: qfloat8
      assistant_lora_path: /cache/hf_cache/zimage_turbo_training_adapter_v2.safetensors
meta:
  name: zimage_lora
  version: '1.0'
